-- ScaleOps6 Agent Tracking Database Schema
-- Complete audit trail and content management for all 96 agents

-- Main agent registry table
CREATE TABLE IF NOT EXISTS agents (
    id VARCHAR(10) PRIMARY KEY,  -- e.g., "1-1", "2-3"
    agent_key VARCHAR(5),         -- e.g., "1a", "2c"
    name VARCHAR(255) NOT NULL,
    description TEXT,
    block_number INT,
    subcomponent_number INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_block (block_number),
    INDEX idx_subcomponent (block_number, subcomponent_number)
);

-- Agent-generated educational content
CREATE TABLE IF NOT EXISTS agent_educational_content (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subcomponent_id VARCHAR(10),
    agent_id VARCHAR(10),
    title VARCHAR(255),
    executive_summary TEXT,
    what_content TEXT,
    why_content TEXT,
    how_content JSON,  -- Stores implementation steps as JSON
    examples JSON,     -- Stores examples as JSON
    metrics JSON,      -- Stores metrics as JSON
    best_practices JSON,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_subcomponent (subcomponent_id),
    INDEX idx_generated (generated_at)
);

-- Workspace questions generated by agents
CREATE TABLE IF NOT EXISTS agent_workspace_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subcomponent_id VARCHAR(10),
    agent_id VARCHAR(10),
    question_id VARCHAR(20),
    dimension VARCHAR(255),
    question TEXT,
    question_type VARCHAR(50),  -- 'scale', 'textarea', 'select', etc.
    weight INT,
    required BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_subcomponent (subcomponent_id)
);

-- User workspace answers
CREATE TABLE IF NOT EXISTS workspace_answers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50),
    subcomponent_id VARCHAR(10),
    question_id VARCHAR(20),
    answer TEXT,
    score INT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_subcomponent (user_id, subcomponent_id),
    INDEX idx_submitted (submitted_at)
);

-- Agent analysis results
CREATE TABLE IF NOT EXISTS agent_analysis_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subcomponent_id VARCHAR(10),
    agent_id VARCHAR(10),
    user_id VARCHAR(50),
    total_score DECIMAL(5,2),
    performance_level VARCHAR(50),
    dimension_scores JSON,  -- Detailed scores per dimension
    strengths JSON,
    improvements JSON,
    recommendations JSON,
    next_steps JSON,
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_user_subcomponent (user_id, subcomponent_id),
    INDEX idx_score (total_score),
    INDEX idx_analyzed (analyzed_at)
);

-- Resource templates generated by agents
CREATE TABLE IF NOT EXISTS agent_resource_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subcomponent_id VARCHAR(10),
    agent_id VARCHAR(10),
    template_name VARCHAR(255),
    template_type VARCHAR(50),  -- 'assessment', 'action_plan', 'guide', etc.
    description TEXT,
    sections JSON,  -- Template structure as JSON
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_subcomponent (subcomponent_id),
    INDEX idx_type (template_type)
);

-- Template outputs (processed templates with user data)
CREATE TABLE IF NOT EXISTS template_outputs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subcomponent_id VARCHAR(10),
    agent_id VARCHAR(10),
    user_id VARCHAR(50),
    template_id INT,
    output_content JSON,  -- Generated content
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    FOREIGN KEY (template_id) REFERENCES agent_resource_templates(id),
    INDEX idx_user_subcomponent (user_id, subcomponent_id),
    INDEX idx_generated (generated_at)
);

-- Score history tracking
CREATE TABLE IF NOT EXISTS score_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50),
    subcomponent_id VARCHAR(10),
    agent_id VARCHAR(10),
    block_number INT,
    score DECIMAL(5,2),
    previous_score DECIMAL(5,2),
    improvement DECIMAL(5,2),
    dimension_scores JSON,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_user_subcomponent (user_id, subcomponent_id),
    INDEX idx_block (block_number),
    INDEX idx_recorded (recorded_at)
);

-- Comprehensive audit trail
CREATE TABLE IF NOT EXISTS agent_audit_trail (
    id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id VARCHAR(10),
    agent_name VARCHAR(255),
    subcomponent_id VARCHAR(10),
    block_number INT,
    action VARCHAR(100),  -- 'content_generated', 'workspace_analyzed', 'template_processed', etc.
    user_id VARCHAR(50),
    data JSON,  -- Additional context data
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_agent (agent_id),
    INDEX idx_subcomponent (subcomponent_id),
    INDEX idx_action (action),
    INDEX idx_timestamp (timestamp),
    INDEX idx_user (user_id)
);

-- Agent performance metrics
CREATE TABLE IF NOT EXISTS agent_performance_metrics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id VARCHAR(10),
    total_analyses INT DEFAULT 0,
    average_score DECIMAL(5,2),
    success_rate DECIMAL(5,2),  -- Percentage of analyses with score > 75
    total_templates_generated INT DEFAULT 0,
    total_outputs_created INT DEFAULT 0,
    last_active TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_agent (agent_id),
    INDEX idx_performance (average_score, success_rate)
);

-- Block-level aggregated data
CREATE TABLE IF NOT EXISTS block_performance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    block_number INT,
    block_name VARCHAR(255),
    total_subcomponents INT,
    average_score DECIMAL(5,2),
    completion_rate DECIMAL(5,2),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_block (block_number),
    INDEX idx_score (average_score)
);

-- User progress tracking
CREATE TABLE IF NOT EXISTS user_progress (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50),
    block_number INT,
    subcomponents_completed INT,
    total_subcomponents INT,
    average_score DECIMAL(5,2),
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user (user_id),
    INDEX idx_block (block_number),
    INDEX idx_progress (subcomponents_completed, total_subcomponents)
);

-- Agent recommendations tracking
CREATE TABLE IF NOT EXISTS agent_recommendations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id VARCHAR(10),
    user_id VARCHAR(50),
    subcomponent_id VARCHAR(10),
    recommendation_type VARCHAR(50),
    recommendation TEXT,
    priority VARCHAR(20),  -- 'Critical', 'High', 'Medium', 'Low'
    status VARCHAR(20) DEFAULT 'Open',  -- 'Open', 'In Progress', 'Completed'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    FOREIGN KEY (agent_id) REFERENCES agents(id),
    INDEX idx_user (user_id),
    INDEX idx_status (status),
    INDEX idx_priority (priority)
);

-- Insert all 96 agents into the registry
INSERT INTO agents (id, agent_key, name, description, block_number, subcomponent_number) VALUES
-- Block 1: Mission Discovery
('1-1', '1a', 'Problem Definition Evaluator', 'Expert in assessing problem clarity and market relevance', 1, 1),
('1-2', '1b', 'Mission Alignment Advisor', 'Evaluates mission clarity and team alignment', 1, 2),
('1-3', '1c', 'VoC Synthesizer', 'Voice of Customer analysis and synthesis expert', 1, 3),
('1-4', '1d', 'Team Gap Identifier', 'Analyzes team composition and capability gaps', 1, 4),
('1-5', '1e', 'Market Mapper', 'Market landscape and opportunity assessment expert', 1, 5),
('1-6', '1f', 'Launch Plan Assessor', 'Evaluates go-to-market launch readiness and planning', 1, 6),

-- Block 2: Customer Insights
('2-1', '2a', 'Interview Cadence Analyzer', 'Evaluates customer interview frequency and quality', 2, 1),
('2-2', '2b', 'Persona Framework Builder', 'Assesses buyer and user persona development', 2, 2),
('2-3', '2c', 'Pain Point Mapper', 'Maps and prioritizes customer pain points', 2, 3),
('2-4', '2d', 'JTBD Specialist', 'Jobs-to-be-Done framework implementation expert', 2, 4),
('2-5', '2e', 'Signal Grader', 'Evaluates strength of customer demand signals', 2, 5),
('2-6', '2f', 'Insight Loop Manager', 'Manages continuous customer insight gathering', 2, 6),

-- Block 3: Strategic Prioritization
('3-1', '3a', 'Use Case Scorer', 'Evaluates and prioritizes use cases', 3, 1),
('3-2', '3b', 'Segment Tier Analyst', 'Analyzes and tiers customer segments', 3, 2),
('3-3', '3c', 'Prioritization Expert', 'Masters prioritization frameworks and decisions', 3, 3),
('3-4', '3d', 'Tradeoff Tracker', 'Documents and analyzes strategic tradeoffs', 3, 4),
('3-5', '3e', 'Hypothesis Validator', 'Tests and validates strategic hypotheses', 3, 5),
('3-6', '3f', 'Decision Archivist', 'Documents and learns from strategic decisions', 3, 6),

-- Block 4: Prototype Launch
('4-1', '4a', 'Feature Matrix Builder', 'Creates and manages feature prioritization matrices', 4, 1),
('4-2', '4b', 'Technical Scope Expert', 'Defines and manages technical scope boundaries', 4, 2),
('4-3', '4c', 'Pilot Group Selector', 'Identifies and manages pilot customer groups', 4, 3),
('4-4', '4d', 'QA Criteria Setter', 'Establishes quality assurance standards and processes', 4, 4),
('4-5', '4e', 'Timeline Planner', 'Creates and manages project timelines', 4, 5),
('4-6', '4f', 'Post-Mortem Analyst', 'Conducts thorough post-launch analysis', 4, 6),

-- Block 5: Early Adopter Wins
('5-1', '5a', 'Early Win Validator', 'Validates and documents early customer wins', 5, 1),
('5-2', '5b', 'ROI Calculator', 'Calculates and validates customer ROI', 5, 2),
('5-3', '5c', 'Use Case Analyst', 'Analyzes successful use case implementations', 5, 3),
('5-4', '5d', 'Testimonial Curator', 'Collects and optimizes customer testimonials', 5, 4),
('5-5', '5e', 'Win Criteria Mapper', 'Maps and tracks win criteria across customers', 5, 5),
('5-6', '5f', 'Deal Debrief Expert', 'Conducts thorough deal debriefs and analysis', 5, 6),

-- Block 6: Customer Engagement Flywheel
('6-1', '6a', 'Usage Heatmap Analyst', 'Analyzes product usage patterns and engagement', 6, 1),
('6-2', '6b', 'Milestone Tracker', 'Tracks customer success milestones', 6, 2),
('6-3', '6c', 'CS Dashboard Builder', 'Creates customer success dashboards and metrics', 6, 3),
('6-4', '6d', 'Activation Expert', 'Optimizes customer activation and onboarding', 6, 4),
('6-5', '6e', 'Feedback Collector', 'Systematically collects and processes feedback', 6, 5),
('6-6', '6f', 'Power User Analyst', 'Identifies and nurtures power users', 6, 6),

-- Block 7: Quantifiable Impact
('7-1', '7a', 'Time/Cost Analyst', 'Quantifies time and cost savings delivered', 7, 1),
('7-2', '7b', 'Revenue Impact Tracker', 'Tracks revenue impact and growth metrics', 7, 2),
('7-3', '7c', 'Productivity Measurer', 'Measures productivity improvements', 7, 3),
('7-4', '7d', 'Retention Analyst', 'Analyzes customer retention and churn', 7, 4),
('7-5', '7e', 'System Reduction Expert', 'Tracks system consolidation and simplification', 7, 5),
('7-6', '7f', 'Friction Analyzer', 'Identifies and eliminates customer friction', 7, 6),

-- Block 8: Customer Success Expansion
('8-1', '8a', 'Upsell Funnel Designer', 'Designs and optimizes upsell funnels', 8, 1),
('8-2', '8b', 'Team Expansion Tracker', 'Tracks account team expansion', 8, 2),
('8-3', '8c', 'Organic Growth Analyst', 'Analyzes organic growth drivers', 8, 3),
('8-4', '8d', 'Champion Mapper', 'Identifies and nurtures customer champions', 8, 4),
('8-5', '8e', 'Sentiment Tracker', 'Tracks and analyzes customer sentiment', 8, 5),
('8-6', '8f', 'Renewal Readiness Expert', 'Ensures renewal readiness and success', 8, 6),

-- Block 9: Proof Execution
('9-1', '9a', 'Inbound Conversion Analyst', 'Optimizes inbound lead conversion', 9, 1),
('9-2', '9b', 'Outbound Performance Tracker', 'Tracks outbound sales performance', 9, 2),
('9-3', '9c', 'Channel Economics Expert', 'Analyzes channel economics and efficiency', 9, 3),
('9-4', '9d', 'Discovery Call Evaluator', 'Evaluates discovery call effectiveness', 9, 4),
('9-5', '9e', 'Demo-to-Close Optimizer', 'Optimizes demo to close conversion', 9, 5),
('9-6', '9f', 'Founder Sales Analyst', 'Analyzes founder-led sales effectiveness', 9, 6),

-- Block 10: Sales Team Empowerment
('10-1', '10a', 'Enablement Asset Manager', 'Manages sales enablement assets and content', 10, 1),
('10-2', '10b', 'Rep Ramp Planner', 'Optimizes sales rep onboarding and ramp', 10, 2),
('10-3', '10c', 'Win/Loss Analyst', 'Conducts win/loss analysis', 10, 3),
('10-4', '10d', 'Objection Handler', 'Masters objection handling strategies', 10, 4),
('10-5', '10e', 'ICP Filter Expert', 'Defines and enforces ideal customer profile', 10, 5),
('10-6', '10f', 'Sales Call Librarian', 'Manages sales call recordings and insights', 10, 6),

-- Block 11: High Performance Teams
('11-1', '11a', 'Scorecard Designer', 'Designs performance scorecards and metrics', 11, 1),
('11-2', '11b', 'Quota Structure Expert', 'Designs and manages quota systems', 11, 2),
('11-3', '11c', 'Deal Review Manager', 'Manages deal review processes', 11, 3),
('11-4', '11d', 'Forecast Framework Builder', 'Builds accurate forecasting systems', 11, 4),
('11-5', '11e', 'Coaching Loop Designer', 'Designs sales coaching programs', 11, 5),
('11-6', '11f', 'Talent Gap Analyst', 'Identifies and addresses talent gaps', 11, 6),

-- Block 12: Retention Systems
('12-1', '12a', 'Onboarding Optimizer', 'Optimizes customer onboarding experience', 12, 1),
('12-2', '12b', 'Activation Tracker', 'Tracks customer activation metrics', 12, 2),
('12-3', '12c', 'Success Playbook Builder', 'Creates customer success playbooks', 12, 3),
('12-4', '12d', 'Escalation Manager', 'Manages customer escalations', 12, 4),
('12-5', '12e', 'Renewal Pipeline Expert', 'Manages renewal pipeline and forecasting', 12, 5),
('12-6', '12f', 'Churn Root-Cause Analyst', 'Analyzes root causes of customer churn', 12, 6),

-- Block 13: Market Domination Strategies
('13-1', '13a', 'Category Narrative Designer', 'Creates compelling category narratives', 13, 1),
('13-2', '13b', 'Strategic Moat Builder', 'Builds competitive moats and barriers', 13, 2),
('13-3', '13c', 'Ecosystem Mapper', 'Maps and leverages ecosystem partnerships', 13, 3),
('13-4', '13d', 'Competitor Monitor', 'Monitors and analyzes competitive landscape', 13, 4),
('13-5', '13e', 'Brand Architect', 'Builds and manages brand strategy', 13, 5),
('13-6', '13f', 'Defensive GTM Strategist', 'Develops defensive go-to-market strategies', 13, 6),

-- Block 14: Operational Infrastructure
('14-1', '14a', 'System Architecture Expert', 'Designs scalable system architecture', 14, 1),
('14-2', '14b', 'Revenue Engine Mapper', 'Maps and optimizes revenue operations', 14, 2),
('14-3', '14c', 'Dashboard Designer', 'Creates operational dashboards', 14, 3),
('14-4', '14d', 'Tool Consolidator', 'Optimizes and consolidates tool stack', 14, 4),
('14-5', '14e', 'RevOps Playbook Builder', 'Creates revenue operations playbooks', 14, 5),
('14-6', '14f', 'SLA Policy Manager', 'Manages service level agreements', 14, 6),

-- Block 15: Leadership Expansion
('15-1', '15a', 'VP Hiring Expert', 'Manages executive hiring process', 15, 1),
('15-2', '15b', 'Succession Planner', 'Develops succession planning programs', 15, 2),
('15-3', '15c', 'Executive Cadence Manager', 'Manages executive meeting rhythms', 15, 3),
('15-4', '15d', 'Culture Health Tracker', 'Monitors organizational culture health', 15, 4),
('15-5', '15e', 'Org Chart Designer', 'Designs organizational structures', 15, 5),
('15-6', '15f', 'DEI Integration Specialist', 'Integrates diversity, equity, and inclusion', 15, 6),

-- Block 16: Global & Expansion Opportunities
('16-1', '16a', 'Market Entry Analyst', 'Analyzes new market entry opportunities', 16, 1),
('16-2', '16b', 'Localization Expert', 'Manages product and content localization', 16, 2),
('16-3', '16c', 'International Pricing Strategist', 'Develops international pricing strategies', 16, 3),
('16-4', '16d', 'Compliance Tracker', 'Manages international compliance requirements', 16, 4),
('16-5', '16e', 'Geo-GTM Specialist', 'Develops geography-specific GTM strategies', 16, 5),
('16-6', '16f', 'Expansion Risk Assessor', 'Assesses and mitigates expansion risks', 16, 6);

-- Initialize block performance data
INSERT INTO block_performance (block_number, block_name, total_subcomponents) VALUES
(1, 'Mission Discovery', 6),
(2, 'Customer Insights', 6),
(3, 'Strategic Prioritization', 6),
(4, 'Prototype Launch', 6),
(5, 'Early Adopter Wins', 6),
(6, 'Customer Engagement Flywheel', 6),
(7, 'Quantifiable Impact', 6),
(8, 'Customer Success Expansion', 6),
(9, 'Proof Execution', 6),
(10, 'Sales Team Empowerment', 6),
(11, 'High Performance Teams', 6),
(12, 'Retention Systems', 6),
(13, 'Market Domination Strategies', 6),
(14, 'Operational Infrastructure', 6),
(15, 'Leadership Expansion', 6),
(16, 'Global & Expansion Opportunities', 6);

-- Create views for reporting
CREATE VIEW agent_activity_summary AS
SELECT 
    a.id,
    a.name,
    a.block_number,
    COUNT(DISTINCT aat.id) as total_actions,
    COUNT(DISTINCT aar.id) as total_analyses,
    AVG(aar.total_score) as avg_score,
    MAX(aat.timestamp) as last_activity
FROM agents a
LEFT JOIN agent_audit_trail aat ON a.id = aat.agent_id
LEFT JOIN agent_analysis_results aar ON a.id = aar.agent_id
GROUP BY a.id, a.name, a.block_number;

CREATE VIEW block_completion_status AS
SELECT 
    bp.block_number,
    bp.block_name,
    bp.total_subcomponents,
    COUNT(DISTINCT sh.subcomponent_id) as completed_subcomponents,
    AVG(sh.score) as average_score,
    MAX(sh.recorded_at) as last_activity
FROM block_performance bp
LEFT JOIN score_history sh ON bp.block_number = sh.block_number
GROUP BY bp.block_number, bp.block_name, bp.total_subcomponents;